steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        asia-south1-docker.pkg.dev/k8s:${SHORT_SHA}
      - '-f'
      - Dockerfile
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        asia-south1-docker.pkg.dev/k8s:${SHORT_SHA}
timeout: 3600s
images:
  - >-
    asia-south1-docker.pkg.dev/k8s:${SHORT_SHA}

logsBucket: '${_LOGS_BUCKET_NAME}'
options:
  logging: CLOUD_LOGGING_ONLY

    #test1
