steps:
#step1
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        asia-south1-docker.pkg.dev/ivory-nectar-448718-j3/k8s-test/nginx:$COMMIT_SHA
      - '-f'
      - Dockerfile
      - .
 #step2
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        asia-south1-docker.pkg.dev/ivory-nectar-448718-j3/k8s-test/nginx:$COMMIT_SHA
timeout: 3600s
images:
  - >-
    asia-south1-docker.pkg.dev/ivory-nectar-448718-j3/k8s-test/nginx:$COMMIT_SHA

logsBucket: 'ci-cd-k8s'

#Step3
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - 'set'
    - 'image'
    - 'deployment/k8s-test1'
    - 'k8s-test1=asia-south1-docker.pkg.dev/ivory-nectar-448718-j3/k8s-test/nginx:$COMMIT_SHA'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-f'
    - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'
    #test1
