steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        asia-south1-docker.pkg.dev/k8s:v1
      - '-f'
      - Dockerfile
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        asia-south1-docker.pkg.dev/k8s:v1
timeout: 3600s
images:
  - >-
    asia-south1-docker.pkg.dev/k8s:v1

logsBucket: 'ci-cd-k8s'

    #test1
