steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'asia-south1-docker.pkg.dev/ivory-nectar-448718-j3/k8s-test/nginx:$COMMIT_SHA'
      - '-f'
      - Dockerfile
      - .

  # Step 2: Push the Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'asia-south1-docker.pkg.dev/ivory-nectar-448718-j3/k8s-test/nginx:$COMMIT_SHA'

timeout: 3600s
images:
  - 'asia-south1-docker.pkg.dev/ivory-nectar-448718-j3/k8s-test/nginx:$COMMIT_SHA'

logsBucket: 'ci-cd-k8s'
