steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        asia-south1-docker.pkg.dev/ivory-nectar-448718-j3/k8s-test/nginx:v1
      - '-f'
      - Dockerfile
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        asia-south1-docker.pkg.dev/ivory-nectar-448718-j3/k8s-test/nginx:v1
timeout: 3600s
images:
  - >-
    asia-south1-docker.pkg.dev/ivory-nectar-448718-j3/k8s-test/nginx:v1

logsBucket: 'ci-cd-k8s'

    #test1
