apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/ivory-nectar-448718-j3/locations/us-central1/clusters/autopilot-cluster-1
